version: '3'

services:
  psql:
    image: postgres
    container_name: psql_todo-rails
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todos_graphql_api_production